apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcdyuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abcdyuh
  template:
    metadata:
      labels:
        app: abcdyuh
    spec:
      containers:
      - image: okteto.dev/abcdyuh:latest
        name: abcdyuh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7a3c107a-400e-4a55-9442-d3e8aed0efb6"
        - name: Vless_Path
          value: "/7a3c107a-400e-4a55-9442-d3e8aed0efb6"
        - name: Vmess_UUID
          value: "d1c135d6-488d-4ec9-a691-2c314780305f"
        - name: Vmess_Path
          value: "/d1c135d6-488d-4ec9-a691-2c314780305f"
        - name: Share_Path
          value: "/v2link"
